spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client-secret}
        provider:
          google:
            redirectUri: http://localhost:8080/login/oauth2/code/google
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  rabbitmq:
    template:
      exchange: tacocloud.order
      routing-key: kitchens.central
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic


logging:
  file:
    path: /var/logs/
    file: TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
      security: DEBUG



tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: 1L0v3T4c0s
    poll-rate: 10000
  api:
    url: http://localhost:8080/orders/fromEmail